### ISSUE TITLE
Problem to install luarocks

### ISSUE THREAD

**Issue by EvandroLG** [luarocks/luarocks#754] opened 2017-12-21 02:45 UTC
When I try to run `tar zxpf luarocks-2.4.3.tar.gz`, I get the following output:

```sh
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```
Is there some issue with the file from this link http://luarocks.org/releases/luarocks-2.4.3.tar.gz?

**Comment by hishamhm** [comment] 2018-01-02 13:54
> Is there some issue with the file from this link http://luarocks.org/releases/luarocks-2.4.3.tar.gz?

Not that I can tell! I was not able to reproduce your problem. The file downloads and unpacks fine for me. I'm closing this for now, feel free to reopen if the problem persists.

**Closed by hishamhm** 2018-01-02 13:54 UTC

**Comment by danieldonoghue** [comment] 2018-04-19 06:45
I, too, have this problem. this might help....

```
$ curl -o luarocks-2.4.4.tar.gz https://luarocks.org/releases/luarocks-2.4.4.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   167  100   167    0     0    205      0 --:--:-- --:--:-- --:--:--   205

$ file luarocks-2.4.4.tar.gz
luarocks-2.4.4.tar.gz: HTML document text, ASCII text, with CRLF line terminators

$ cat luarocks-2.4.4.tar.gz
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>openresty/1.7.10.1</center>
</body>
</html>

```

**Comment by ildar** [comment] 2018-04-19 09:32
May I?
there's something wrong with your curl. Try adding `--max-redirs 50` (it
*should* be 50 by default).

**Comment by daurnimator** [comment] 2018-04-20 00:01
> there's something wrong with your curl. Try adding `--max-redirs 50` (it *should* be 50 by default).

`max-redirs` will be fine; what is missing is the `-L` flag to curl which tells it to follow redirects at all.

**Comment by hjjayakrishnan** [comment] 2024-07-10 22:20
@hishamhm This issue is still present and as [codeforlibre](https://github.com/codeforlibre) commented adding -L helps. Could you please update the install instructions as well?
