### ISSUE TITLE
Unable to use Luarocks with MingW-64 build Lua 5.3.4 

### ISSUE THREAD

**Issue by Zethalion** [luarocks/luarocks#708] opened 2017-05-30 14:20 UTC
I build Lua using MSYS-2:

make clean
make mingw ([build log](https://pastebin.com/raw/QAUpGRJw))
make install INSTALL_TOP=c:/lua/5.3 TO_BIN="lua.exe luac.exe lua53.dll"

Next I install Luarocks:

install /mw /lv 5.3 /lua c:\lua\5.3 /p c:\lua\rocks
 
> Admin privileges available for installing
> Looking for Lua interpreter
>     checking c:\lua\5.3
>        Found lua.exe, testing it...
> Interpreter found, now looking for link libraries...
>     checking for c:\lua\5.3\lua5.3.lib
>     checking for c:\lua\5.3\lua53.lib
>     checking for c:\lua\5.3\lua5.3.dll
>     checking for c:\lua\5.3\lua53.dll
>     checking for c:\lua\5.3\liblua.dll.a
>     checking for c:\lua\5.3\lib\lua5.3.lib
>     checking for c:\lua\5.3\lib\lua53.lib
>     checking for c:\lua\5.3\lib\lua5.3.dll
>     checking for c:\lua\5.3\lib\lua53.dll
>     checking for c:\lua\5.3\lib\liblua.dll.a
>     checking for c:\lua\5.3\bin\lua5.3.lib
>     checking for c:\lua\5.3\bin\lua53.lib
>     checking for c:\lua\5.3\bin\lua5.3.dll
>     checking for c:\lua\5.3\bin\lua53.dll
>        Found lua53.dll
> Link library found, now looking for headers...
>     checking for c:\lua\5.3\include\lua\5.3\lua.h
>     checking for c:\lua\5.3\include\lua53\lua.h
>     checking for c:\lua\5.3\include\lua5.3\lua.h
>     checking for c:\lua\5.3\include\lua.h
>        Found lua.h
> Headers found, checking runtime to use...
> *** WARNING ***: could not analyse the runtime used, defaulting to MSVCR80
> Runtime check completed.
> 
>
> System check results
>
> 
> Will configure LuaRocks with the following paths:
> LuaRocks        : c:\lua\rocks
> Config file     : c:\lua\rocks\config-5.3.lua
> Rocktree        : c:\lua\5.3\
> 
> Lua interpreter : c:\lua\5.3\bin\lua.exe
>     binaries    : c:\lua\5.3\bin
>     libraries   : c:\lua\5.3\bin
>     includes    : c:\lua\5.3\include
>     architecture: x86_64
>     binary link : lua53.dll with runtime MSVCR80.dll
> 
> Compiler        : MinGW (make sure it is in your path before using LuaRocks)
> 
> Press <ENTER> to start installing, or press <CTRL>+<C> to abort. Use install /? for installation options.

What worries me is this part:

> *** WARNING ***: could not analyse the runtime used, defaulting to MSVCR80

I explicitly entered the /mw parameter but the installer seems to ignore it concerning the library lua53.dll

I continu installing Luarocks and I run it:

> luarocks
> Your version of Lua does not support io.popen,
> which is required by LuaRocks. Please check your Lua installation.

What did I do wrong and how can I correct it?

*edit: added Lua build log link

**Comment by hishamhm** [comment] 2017-05-30 14:25
@Tieske, any ideas? When given /mw the installer should never revert to MSVC (better to fail instead and report what's missing)

**Comment by hishamhm** [comment] 2017-05-30 15:15
About the io.popen error message, what happens when you start the Lua interpreter you built and run `print(io. popen)`? 

If it says nil, then it is a bug in the Lua makefile.

**Comment by hishamhm** [comment] 2017-05-30 15:16
(sorry, my phone added a space after the dot. It should say `print(io.popen)`)

**Comment by Zethalion** [comment] 2017-05-30 15:21
I tried that and it indeed returned nil. 

I guess I need to link this issue to the Lua devs as well?

**Comment by hishamhm** [comment] 2017-05-30 15:58
Yes, and the way to do this is via the Lua mailing list.

**Comment by Zethalion** [comment] 2017-05-30 16:05
I'll do that after @Tieske has put his eye on this since I followed his MinGW instructions to build Lua.

**Comment by Tieske** [comment] 2017-06-04 22:54
sorry for the late reply, been talking to @hishamhm all day and didn't even touch on this. Will have a look shortly (no Windows PC at hand right now)

**Comment by Tieske** [comment] 2017-06-04 22:59
@Zethalion what versions of the toolchain did you use? Might be related to a newer version.

Also can you post me the binaries (lua `.exe` and `.dll` files) somewhere?

**Comment by Tieske** [comment] 2017-06-13 09:40
@Zethalion ping can you provide me the binaries?

**Comment by Zethalion** [comment] 2017-06-13 10:30
Sorry for the late reply. I'll upload them somewhere today.

**Comment by Tieske** [comment] 2017-06-15 22:18
So I ran `pe-parser` on those binaries;

```
C:\test\zethalion>pe-parser -dump lua53.dll
Now analyzing: 'lua53.dll'
SizeOfHeaders               : 400
SizeOfInitializedData       : 2cc00
Machine                     : IMAGE_FILE_MACHINE_AMD64
Subsystem                   : IMAGE_SUBSYSTEM_WINDOWS_CUI
SizeOfUninitializedData     : 200
NumberOfRvaAndSizes         : 10
DllCharacteristics          : 0 (flag field)
CheckSum                    : 36439
MajorLinkerVersion          : 2
Characteristics             : 2226 (flag field)
MinorOperatingSystemVersion : 0
MajorSubsystemVersion       : 5
AddressOfEntryPoint         : 21a50
SizeOfHeapReserve           : 100000
PointerToSymbolTable        : 2d000
FileAlignment               : 200
SizeOfStackCommit           : 1000
TimeDateStamp               : a750a748
MinorLinkerVersion          : 19
Magic                       : PE32+
ImageBase                   : 487a00000
NumberOfSections            : a
SizeOfCode                  : 21200
MajorImageVersion           : 0
MinorSubsystemVersion       : 2
SizeOfImage                 : 33000
SizeOfStackReserve          : 200000
SizeOfOptionalHeader        : f0
LoaderFlags                 : 0
BaseOfCode                  : 1000
SizeOfHeapCommit            : 1000
Win32VersionValue           : 0
MinorImageVersion           : 0
SectionAlignment            : 1000
NumberOfSymbols             : 5a
MajorOperatingSystemVersion : 4
DataDirectory (RVA, size):
   Entry 0 00030000 00000dcd ExportTable
   Entry 1 00031000 00000aa4 ImportTable
   Entry 2 00000000 00000000 ResourceTable
   Entry 3 0002b000 00001f8c ExceptionTable
   Entry 4 00000000 00000000 CertificateTable
   Entry 5 00032000 00000410 BaseRelocationTable
   Entry 6 0002a000 0000001c Debug
   Entry 7 00000000 00000000 Architecture
   Entry 8 00000000 00000000 GlobalPtr
   Entry 9 00000000 00000000 TLSTable
   Entry a 00000000 00000000 LoadConfigTable
   Entry b 00000000 00000000 BoundImport
   Entry c 000312e4 000002a8 IAT
   Entry d 00000000 00000000 DelayImportDescriptor
   Entry e 00000000 00000000 CLRRuntimeHeader
   Entry f 00000000 00000000 Reserved
Sections:
idx name     RVA      VSize    Offset   RawSize
  1 .text    00001000 00021068 00000400 00021200
  2 .data    00023000 00000068 00021600 00000200
  3 .rdata   00024000 00005430 00021800 00005600
  4 .buildid 0002a000 00000035 00026e00 00000200
  5 .pdata   0002b000 00001f8c 00027000 00002000
  6 .xdata   0002d000 00001e50 00029000 00002000
  7 .bss     0002f000 000001d0 00000000 00000000
  8 .edata   00030000 00000dcd 0002b000 00000e00
  9 .idata   00031000 00000aa4 0002be00 00000c00
  10 .reloc   00032000 00000410 0002ca00 00000600
Imports:
   msys-2.0.dll
   KERNEL32.dll
Done analyzing: 'lua53.dll'

C:\test\zethalion>
```
And in the `import` section it's clear that it is not linked to any of the Microsoft runtime dll's (the `msvcrxxx.dll` files). But instead it's using the `msys-2.0.dll`.

This is what causes the installer to fail.

Question is now how to handle this case, is this simply `MinGW` from LuaRocks perspective, or an entire new toolchain to support? eg. MSYS, MinGW, and Microsoft? We'll probably have to test that first.

from https://sourceforge.net/p/msys2/mailman/message/32344292/ : 

>You need to understand that mingw-w64-i686-gcc and msys2-gcc is different compilers. Msys2-gcc is modified Cygwin GCC.
>Building with msys2-gcc you always get dependency from msys-2.0.dll. At this time there are no static msys-2.0 library only shared.
>The mingw-w64-i686-gcc is true native windows mingw-w64 toolchain.



some more info: http://www.davidegrayson.com/windev/msys2/

**Comment by Zethalion** [comment] 2017-06-15 23:18
Thank you for your time looking into this. To me personally I should switch compiler. Mainly get away from MSYS-2 which I choose because MSYS (+ MinGW ) hasn't been updates for years. I am to much a novice to tell anything about MSYS-2 worthy to support but the looks are promising since it still is actively being developed.

For now I'll move to pure MinGW and try again. I'll report back soon with results.

**Comment by Hydroque** [comment] 2017-12-18 03:27
MingW support is definitely might be an issue with me too. 

My config
```
rocks_trees = {
    { name = [[user]],
         root    = home..[[/luarocks]],
    },
    { name = [[system]],
         root    = [[C:\Program Files (x86)\LuaRocks\systree]],
    },
}
variables = {
    MSVCRT = 'MSVCR80',
    LUALIB = 'liblua.a'
}
verbose = true   -- set to 'true' to enable verbose output
```

**Comment by Tieske** [comment] 2017-12-24 08:26
@Hydroque since you have `MSVCRT = 'MSVCR80'` in your config file, your enviornment has been set up for the MS toolchain

@Zethalion can we close this issue?

**Comment by Hydroque** [comment] 2017-12-24 08:33
No we can't. Building with MINGW doesn't automatically take MSVCRT out.

**Comment by Zethalion** [comment] 2017-12-24 13:47
I'd like to see MSYS2 support since that suite is not abandoned by it's developer. It's up to you to decide to label this 'wontfix' and close this. The idea of using a years old compiler while OS's continue to change over the years, might one day the make might end up spouting binaries that are not secure, incompatible.

**Comment by Tieske** [comment] 2017-12-28 13:33
@Hydroque What I meant is that if the installer put that line in your config file, then you installed using the MS toolchain. To install using the MinGW toolchain, you must specify the `/mw` command line switch, as per the docs.

**Comment by Hydroque** [comment] 2017-12-28 14:04
I did.

**Comment by Tieske** [comment] 2017-12-29 08:09
@Hydroque the installer will analyse your Lua executable and find the runtime lib it was compiled against. If it cannot find it it will default to the setting you have `MSVCR80`. So you must have compiled the lua executable using a different toolchain?

Something to be fixed probably, if you specifiy `/MW` it should never default back to `MSVCR80` as that makes no sense.

**Comment by Hydroque** [comment] 2017-12-30 05:56
```
C:\Users\CBUD\Desktop\luarocks-2.4.3>dir C:\progra~2\LuaRocks
 Volume in drive C has no label.
 Volume Serial Number is 20F5-21D1

 Directory of C:\progra~2

File Not Found

C:\Users\CBUD\Desktop\luarocks-2.4.3>using %mingw64%

C:\Users\CBUD\Desktop\luarocks-2.4.3>echo %path%
C:\Progra~1\mingw-w64\x86_64-7.1.0-win32-seh-rt_v5-rev0\mingw64\bin;C:\Windows\s
ystem32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShel
l\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\CMake\bin;C:\Program Files (x8
6)\NVIDIA Corporation\PhysX\Common

C:\Users\CBUD\Desktop\luarocks-2.4.3>install /L /MW /F

rem=rem --[[
LuaRocks 2.4.x installer.


========================
== Checking system... ==
========================


Admin privileges available for installing

==========================
== System check results ==
==========================

Will configure LuaRocks with the following paths:
LuaRocks        : C:\Program Files (x86)\LuaRocks
Config file     : C:\Program Files (x86)\LuaRocks\config-5.1.lua
Rocktree        : C:\Program Files (x86)\LuaRocks\systree

Lua interpreter : C:\Program Files (x86)\LuaRocks\lua5.1
    binaries    : C:\Program Files (x86)\LuaRocks
    libraries   : C:\Program Files (x86)\LuaRocks
    includes    : C:\Program Files (x86)\LuaRocks\include
    architecture: x86
    binary link : lua5.1.lib with runtime MSVCR80.dll

Compiler        : MinGW (make sure it is in your path before using LuaRocks)

Press <ENTER> to start installing, or press <CTRL>+<C> to abort. Use install /?
for installation options.


============================
== Installing LuaRocks... ==
============================


Installing LuaRocks in C:\Program Files (x86)\LuaRocks...
Installed the LuaRocks bundled Lua interpreter in C:\Program Files (x86)\LuaRock
s
Created LuaRocks command: C:\Program Files (x86)\LuaRocks\luarocks.bat
Created LuaRocks command: C:\Program Files (x86)\LuaRocks\luarocks-admin.bat

Configuring LuaRocks...
Created LuaRocks site-config file: C:\Program Files (x86)\LuaRocks\lua\luarocks\
site_config_5_1.lua
Created LuaRocks config file: C:\Program Files (x86)\LuaRocks\config-5.1.lua

Creating rocktrees...
Created system rocktree    : "C:\Program Files (x86)\LuaRocks\systree"
Local user rocktree exists : "C:\Users\CBUD\AppData\Roaming\LuaRocks"

Loading registry information for ".rockspec" files

============================
== LuaRocks is installed! ==
============================


You may want to add the following elements to your paths;
Lua interpreter;
  PATH     :   C:\Program Files (x86)\LuaRocks
  PATHEXT  :   .LUA
LuaRocks;
  PATH     :   C:\Program Files (x86)\LuaRocks
  LUA_PATH :   C:\Program Files (x86)\LuaRocks\lua\?.lua;C:\Program Files (x86)\
LuaRocks\lua\?\init.lua
Local user rocktree (Note: %APPDATA% is user dependent);
  PATH     :   %APPDATA%\LuaRocks\bin
  LUA_PATH :   %APPDATA%\LuaRocks\share\lua\5.1\?.lua;%APPDATA%\LuaRocks\share\l
ua\5.1\?\init.lua
  LUA_CPATH:   %APPDATA%\LuaRocks\lib\lua\5.1\?.dll
System rocktree
  PATH     :   C:\Program Files (x86)\LuaRocks\systree\bin
  LUA_PATH :   C:\Program Files (x86)\LuaRocks\systree\share\lua\5.1\?.lua;C:\Pr
ogram Files (x86)\LuaRocks\systree\share\lua\5.1\?\init.lua
  LUA_CPATH:   C:\Program Files (x86)\LuaRocks\systree\lib\lua\5.1\?.dll

Note that the %APPDATA% element in the paths above is user specific and it MUST
be replaced by its actual value.
For the current user that value is: C:\Users\CBUD\AppData\Roaming.



C:\Users\CBUD\Desktop\luarocks-2.4.3>dir C:\progra~2\LuaRocks
 Volume in drive C has no label.
 Volume Serial Number is 20F5-21D1

 Directory of C:\progra~2\LuaRocks

12/30/2017  12:53 AM    <DIR>          .
12/30/2017  12:53 AM    <DIR>          ..
12/18/2017  07:43 PM            94,208 bin2c5.1.exe
12/30/2017  12:53 AM               323 config-5.1.lua
12/30/2017  12:53 AM    <DIR>          include
12/30/2017  12:53 AM    <DIR>          lua
12/18/2017  07:43 PM            22,486 lua.ico
12/18/2017  07:43 PM           167,936 lua5.1.dll
12/18/2017  07:43 PM            45,056 lua5.1.exe
12/18/2017  07:43 PM            26,112 lua5.1.lib
12/18/2017  07:43 PM            11,264 lua51.dll
12/18/2017  07:43 PM            25,974 lua51.lib
12/18/2017  07:43 PM           208,896 luac5.1.exe
12/30/2017  12:53 AM             1,851 luarocks-admin.bat
12/18/2017  07:43 PM               481 luarocks-admin.lua
12/30/2017  12:53 AM             1,845 luarocks.bat
12/18/2017  07:43 PM               885 luarocks.lua
12/18/2017  07:43 PM             1,327 luarocksw.bat
12/18/2017  07:43 PM             1,869 Microsoft.VC80.CRT.manifest
12/18/2017  07:43 PM           479,232 msvcm80.dll
12/18/2017  07:43 PM           548,864 msvcp80.dll
12/18/2017  07:43 PM           626,688 msvcr80.dll
12/18/2017  07:43 PM             4,157 rclauncher.c
12/30/2017  12:53 AM    <DIR>          systree
12/30/2017  12:53 AM    <DIR>          tools
12/18/2017  07:43 PM            35,840 wlua5.1.exe
              20 File(s)      2,305,294 bytes
               6 Dir(s)  238,226,128,896 bytes free

C:\Users\CBUD\Desktop\luarocks-2.4.3>type C:\progra~2\LuaRocks\config-5.1.lua
rocks_trees = {
    { name = [[user]],
         root    = home..[[/luarocks]],
    },
    { name = [[system]],
         root    = [[C:\Program Files (x86)\LuaRocks\systree]],
    },
}
variables = {
    MSVCRT = 'MSVCR80',
    LUALIB = 'lua5.1.lib'
}
verbose = false   -- set to 'true' to enable verbose output

```

**Comment by Hydroque** [comment] 2017-12-30 06:05
Ahh okay. So I concluded that the built in one uses MSVCR80. I don't think it is compiled as part of installation. So thats why the variable exist. However, my compiler is mingw thereof and the problem is I can't compile with VS.

**Comment by Tieske** [comment] 2017-12-30 10:29
@Hydroque I haven't read your post in detail (sorry about that). If it works for you then great. One word of warning though: _never mix runtimes_!

If you're installing packages with MinGW toolchain using `msvcrt.dll`, then your Lua interpreter *MUST* also use that runtime, and not the `MSVCR80.dll`. If you mix those you'll get sporadic and hard to trace errors/segfaults. In that case best to use MinGW to compile the Lua interpreter from source.

Alternatively use some tools that can build you a complete package like https://github.com/Tieske/luawinmulti (that's one I wrote, but there are more)

**Comment by Hydroque** [comment] 2017-12-30 11:15
Yeah read it indepth. You missed the fact that the included pre-build windows lua5.1 that ships with luarocks depends on MSVCR80. I am saying its not necessary to have that and anything of that nature, however, the variables.MSVCRT is defined so that additional things can be built ontop of it. However, this is unexpected and unnecessary behavior when compiling rocks to use with other interpreters.

**Comment by hishamhm** [comment] 2018-03-13 13:42
@Tieske Does the inclusion of db49037aff80f7bc4cec25fdecd642c49ff63252 in the now-released LuaRocks 2.4.4 fix this?

**Comment by Tieske** [comment] 2018-03-14 05:52
The problems in this issue are similar but not the same.

1. @Zethalion had a `lua.exe` build, and the installer couldn't find the runtime, and hence defaulted to `MSVCR80.dll` (that default was chosen because the included Lua executable has been build with that). The toolchain used is MSYS2 by argument that it is under active development/maintenance, which the MinGW toolchain is not anymore.

2. The issue encountered by @tilkinsc is that he tried to use a Lua executable build with `MSVCR80.dll` (I'd assume the LuaRocks bundled one) as the runtime, while specifying the `/MW` flag to use MinGW as compiler. The problem is understandable, but (without checking the docs) probably an rtfm issue (no pun intended).

So where does it leave us:

- PR #759 improved support for the GCC toolchains including the newer still active ones. And it no longer defaults to anything, it just breaks at install time if the compiler cannot be found. Adding MSYS2 is still an option, but not a necessity imo.
- Item 2 is harder to fix. We could check for `msvcrt.dll` as required for the `/MW` switch, but not sure whether that is actually desirable...

@hishamhm so https://github.com/luarocks/luarocks/commit/db49037aff80f7bc4cec25fdecd642c49ff63252 fixes part of the problem.

**Comment by tilkinsc** [comment] 2018-03-23 18:56
I ended up compiling with mingw fine, but the problem was as you said for me. I used a custom lua build with a custom name which could be fixed using prefix and modification of site config iirc before runtime. I had to add what compiler name I used. I figure instead of a /mw switch it could be a /gcc switch and defaultly adds CC and LD to the config. tldr; just needed to tell luarocks what compiler I was using and what my runtime lib was.
I just had no ready information on different things of the config to figure out how to set it up in the build state then.

**Comment by Tieske** [comment] 2018-03-26 07:31
@tilkinsc be aware that MinGW will compile against the `msvcrt` runtime. I don't even know whether it is capable of using the other ones, eg. `msvcr80.dll` at all.
Please check carefully because if at runtime you mix the runtimes, that will wreak havoc. It initially will appear to work, but then later on you'll get sporadic hard to track failures. So best to make sure everything is build using the same toolchain, and the same runtimes.

**Comment by Tieske** [comment] 2018-04-02 10:38
@hisham can we close this one?

**Closed** 2018-04-02 14:27 UTC

**Comment by aryajur** [comment] 2021-07-29 19:09
I am having a similar issue when I installed Luarocks 3.7. I did a bunch of experiments I am listing here:

1. I built Lua 5.4 with mingw64 (msys2 installation). Then installed luarocks 3.7 using install.bat with the /mw option and /lv to 5.4. This did not work. It complained about io.popen not being available but it was there in the lua interpreter.
2. I then restarted with Lua 5.3.6 built with mingw64 (msys2 installation). Got the same problem again.
3. I then restarted again with Lua 5.3.6 built with mingw32 (msys2 installation). This time it worked and I was able to run the command luarocks install dkjson successfully.

Now when I try
`luarocks install luafilesystem`

I get the following:
`Installing https://luarocks.org/luafilesystem-1.8.0-1.src.rock`
`luafilesystem 1.8.0-1 depends on lua >= 5.1 (5.3-1 provided by VM)`
`C:\msys64\usr\bin\gcc.exe -O2 -c -o src/lfs.o -ID:\Milind\Documents\Programs\luarocks_5.3\include src/lfs.c`
`C:\msys64\usr\bin\gcc.exe -shared -o lfs.dll src/lfs.o D:\Milind\Documents\Programs\luarocks_5.3\lib/lua53.dll -lMSVCR80`
`/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lMSVCR80`
`collect2: error: ld returned 1 exit status`
`Error: Build error: Failed compiling module lfs.dll`

So I am not clear why it wants to use MSVCR80. If I compile Luafilesystem manually I am able to compile it without using MSVCR80.

**Comment by tilkinsc** [comment] 2021-07-31 23:44
MSVC* are dlls which contain the microsoft runtime. It wants to use it because luarocks batch file can't customly use a dll to save it's life and you have to do manually edit files. I have them listed in my wiki at https://github.com/tilkinsc/LuaRocks/wiki
