### ISSUE TITLE
hardcoding package.path into binary makes luarocks non-lua-version-agnostic

### ISSUE THREAD

**Issue by daurnimator** [luarocks/luarocks#511] opened 2016-03-09 05:13 UTC
This line: https://github.com/keplerproject/luarocks/blob/28ade76301133abc3b4ea96faefb51fe59f1c3ad/Makefile#L93

On debian, this means that /usr/bin/luarocks contains:

``` lua
package.path = [[/usr/share/lua/5.1/?.lua;]]..package.path
```

Which is a show-stopper for having one luarocks installation handle all lua versions, as this means that running `lua5.3 /usr/bin/luarocks path --bin` results in a path of:

```
export LUA_PATH_5_3='/home/daurnimator/.luarocks/share/lua/5.3/?.lua;/home/daurnimator/.luarocks/share/lua/5.3/?/init.lua;/usr/local/share/lua/5.3/?.lua;/usr/local/share/lua/5.3/?/init.lua;/usr/share/lua/5.1/?.lua;/usr/local/lib/lua/5.3/?.lua;/usr/local/lib/lua/5.3/?/init.lua;/usr/share/lua/5.3/?.lua;/usr/share/lua/5.3/?/init.lua;./?.lua;./?/init.lua'
```

---

This line doesn't seem to exist in other distros (e.g. arch linux); I'm not sure what makes it show up or not.

**Comment by daurnimator** [comment] 2016-03-09 05:53
> This line doesn't seem to exist in other distros (e.g. arch linux); I'm not sure what makes it show up or not.

The `package.path` line appears when you use `make build`, but not if you directly `make install`

Looking at debian, they run `make build` first: https://sources.debian.net/src/luarocks/2.2.0%2Bdfsg-2/debian/rules/#L21
Looking at arch, they run `make` (which does nothing) then `make install`: https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/luarocks

**Comment by raingloom** [comment] 2016-03-10 17:22
I'd also like to know this, as I recently modified a version in the AUR to build with `make build` instead of `make`, because without that it was detecting the incorrect Lua version.

**Comment by hishamhm** [comment] 2016-05-25 04:31
> lua5.3 /usr/bin/luarocks path --bin

This is not the way the script is designed to run. Yes, without that line this would run your binary just fine, but the rest of LuaRocks itself (the luarocks.* modules) will be installed at /usr/share/lua/5.1/, and won't be found causing errors. You'd have to have copies of those LuaRocks modules at the /share/lua/<version>/. 

But if you install LuaRocks twice to get these modules for 5.1 and 5.3, you'll also get `luarocks-5.1` and `luarocks-5.3` in your $PATH, which will work as intended.

**Comment by hishamhm** [comment] 2024-02-18 23:52
Closing this since the current way to use different Lua versions with a LuaRocks installation is `luarocks --lua-version=5.x`, which can be made automatic with `luarocks config lua_version 5.x`.

**Closed by hishamhm** 2024-02-18 23:52 UTC
