### ISSUE TITLE
Package requires lua >= 5.1 but VM is 5.1-1 and install dir shows lua 5.1.5

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [luarocks/luarocks#1259] opened 2021-01-08 21:19 UTC
Just installed luarocks and was able to run `luarocks install lunajson` but am greeted with this error:

```
$luarocks install lunajson
Installing https://luarocks.org/lunajson-1.2.3-1.src.rock

lunajson 1.2.3-1 depends on lua >= 5.1 (5.1-1 provided by VM)
The system cannot find the path specified.
No existing manifest. Attempting to rebuild...
The system cannot find the path specified.
```

I peek into the install dir and see Lua5.1 and running it shows the version is actually Lua 5.1.5.

Shouldn't this package install?

**Comment by daurnimator** [comment] 2021-01-12 15:04
What does your `_VERSION` contain?
`lua -e 'print(_VERSION)'`

**Comment by TheMaverickProgrammer** [comment] 2021-01-12 17:21
`Lua 5.1` which is still within the bounds of the module's requirements or so it says

**Comment by daurnimator** [comment] 2021-01-15 13:40
> 5.1-1 provided by VM

I'm not sure where the `-1` is coming from; and I think luarocks doesn't understand it.

**Comment by siffiejoe** [comment] 2021-01-15 14:54
The `-1` is a (fake) rockspec revision introduced and handled exclusively by luarocks.

**Comment by ethanparsons** [comment] 2022-11-18 20:06
I'm having a very similar problem, but with lua-chartplot and lua-gnuplot. 
`Installing https://luarocks.org/lua-gnuplot-0.3-1.src.rock

lua-gnuplot 0.3-1 depends on lua >= 5.1 (5.1-1 provided by VM)

Error: failed making directory C:/Program Files (x86)/Lua/5.1/systree/lib/luarocks/rocks-5.1/lua-gnuplot/0.3-1/conf`
Has there been a solution to this?

**Comment by TheMaverickProgrammer** [comment] 2022-11-19 20:02
Unfortunately no. I gave up.

**Comment by hishamhm** [comment] 2024-02-19 14:40
`depends on lua >= 5.1 (5.1-1 provided by VM)`

This is not an error message. I'm changing it to `depends on lua >= 5.1 (5.1-1 provided by VM: success)` to make that clearer: https://github.com/luarocks/luarocks/pull/1597

The two failures above are distinct, and unrelated to that: `The system cannot find the path specified` (a Windows error message caused by some command LuaRocks executed), and `failed making directory` (which may be a path permission issue). These could be caused by several things, we'd need more diagnostics.

I will close this issue for now, and if new such errors appear, let's open new issues with the output of LuaRocks with `--verbose` so we can dig it further.

**Closed by hishamhm** 2024-02-19 14:40 UTC
Labels: windows
