### ISSUE TITLE
Cannot remove rock

### ISSUE THREAD

**Issue by aryajur** [luarocks/luarocks#678] opened 2017-03-02 18:53 UTC
Hi,
     I created a rock called many2one. I created the rockspec and the rock and uploaded to Luarocks. It installs fine. It runs fine after installation. But when I try to remove it it give me an error:

C:\Users\mgupta\Documents\Programs\luarocks>luarocks remove many2one
Checking stability of dependencies in the absence of
many2one 1.17.3.1-1...

Removing many2one 1.17.3.1-1...

Error: Could not remove c:\users\mgupta\documents\programs\luarocks\/bin/many2on
e_1_17_3_1_1-many2one.lua: c:\users\mgupta\documents\programs\luarocks\/bin/many
2one_1_17_3_1_1-many2one.lua.bat, c:\users\mgupta\documents\programs\luarocks\/b
in/many2one_1_17_3_1_1-many2one.lua not found

I am not sure if it is a problem with my rockspec or somewhere else. Please help me fix this. I have pasted the rockspec many2one-1.17.3.1-1.rockspec below:
```
package = "many2one"
version = "1.17.3.1-1"
source = {
	url = "git://github.com/aryajur/many2one",
	tag = "1.17.3"
}
description = {
	summary = "Convert application spanning multiple Lua files to 1",
	detailed = [[
		This is a simple script that combines an application written spanning multiple Lua files into a single lua file for easy distribution and running.
	]],
	homepage = "http://milindsweb.amved.com/Many2One.html", 
	license = "MIT" 
}
dependencies = {
	"lua >= 5.1"
}
build = {
	type = "builtin",
	modules = {
		many2one = "../src/many2one.lua"
	},
    install = {
        bin = {
            "../src/many2one.lua",
        },
    },
}
```

**Comment by mpeterv** [comment] 2017-03-02 19:20
This is LuaRocks 2.4.2, right? Are there any files related to many2one inside `c:\users\mgupta\documents\programs\luarocks/bin`?

**Comment by mpeterv** [comment] 2017-03-02 19:41
Nevermind, no more input required, I've reproduced it locally.

**Comment by mpeterv** [comment] 2017-03-02 20:08
The issue is that for commands with names ending with `.lua` Luarocks generates incorrect entry in the manifest. This has been fixed on `luarocks-3` branch, although I didn't realize there was a bug back then: 5e5d324. @hishamhm if we backport that fix with plans to release 2.4.3 we might as well backport some other fixes and features (#652), what do you think?

**Comment by mpeterv** [comment] 2017-03-02 20:13
@aryajur by the way, what's the reason to use `"../src/many2one.lua"` instead of simply `many2one.lua`? The latter should work just as well.

**Comment by aryajur** [comment] 2017-03-02 21:28
Thanks for looking into this so soon. When is Luarocks 3 going to be released? If it is not going to happen soon then yes it would be really good to have the features and fixes done for 2.4.3.
     For the path I put in ../src/many2one.lua becuase I thought that the path should be given relative to the placement of the rockspec in the repository. When I did put just src/many2one.lua and the rockspec was in a subdirectory called rockspec I was not able to make it work using luarocks make (to test it before uploading the rock to luarocks)

**Comment by hishamhm** [comment] 2017-03-02 22:43
@mpeterv I can't really work on it until the end of April, but if you want to backport fixes and tag a new 2.x version before that, I can package and release it.

**Comment by hishamhm** [comment] 2017-03-02 22:44
> For the path I put in ../src/many2one.lua becuase I thought that the path should be given relative to the placement of the rockspec in the repository. When I did put just src/many2one.lua and the rockspec was in a subdirectory called rockspec I was not able to make it work using luarocks make (to test it before uploading the rock to luarocks)

@aryajur Interesting, haven't thought of that issue. Doesn't it work if, from the root of your repository, you do `luarocks make rockspec/many2one-1.17.3.1-1.rockspec` ?

**Comment by hishamhm** [comment] 2024-02-20 20:00
Closing since the rockspec above (with `"src/many2one.lua"` and not `..`) works on LuaRocks 3+

**Closed by hishamhm** 2024-02-20 20:00 UTC
