### ISSUE TITLE
Error when installing: "source and destination are the same file"

### ISSUE THREAD

**Issue by MisterDA** [luarocks/luarocks#1062] opened 2019-07-24 10:30 UTC
Hello,
This might be an issue on my side.
I have this error when I install [love-release][love-release] (newlines are mine).

```sh
luarocks install love-release 2.0.13 --local # error
luarocks install love-release 2.0.11 --local # works
```

```
Error: Build error: Failed installing
src/scripts/macosx.lua in
/home/user/.luarocks/lib/luarocks/rocks-5.3/love-release/2.0.13-1/lua/love-release/scripts/macosx.lua:
The source and destination are the same files
```
Here the error is with `macosx.lua`, but it’s not specific to this file. Sometimes another file aborts the install process.
It did not appear with love-release 2.0.11. It appears with 2.0.12 but the rockspec is buggy. I thought I fixed it in 2.0.13. The diff is:

```diff
diff love-release-2.0.11-1.rockspec love-release-2.0.13-1.rockspec 
2c2
< version = "2.0.11-1"
---
> version = "2.0.13-1"
6c6
<   tag = "v2.0.11",
---
>   tag = "v2.0.13",
```

I don’t know why this is happening. If you can spare some time to help, I’d be very grateful.
Thanks!

[love-release]: https://github.com/MisterDA/love-release

**Comment by Tieske** [comment] 2019-07-24 13:11
I've seen that error repeatedly as well lately. Issuing the exact same command again succeeds the 2nd time for me.

(different rocks though)

**Comment by MisterDA** [comment] 2019-07-24 22:27
> Issuing the exact same command again succeeds the 2nd time for me.

Not with me…

**Comment by doronbehar** [comment] 2019-08-11 09:49
I get this error as well, very annoying since I can't find a way to workaround it. It seems the relevant part in Luarocks' code is here:

https://github.com/luarocks/luarocks/blob/f82627800d09755412bc50cbf9f1f964d1b2c5be/src/luarocks/fs/lua.lua#L390-L400

**Comment by doronbehar** [comment] 2019-08-11 10:01
Git blame points this was written in https://github.com/luarocks/luarocks/commit/c212c884 by @georgeroman as the author and @hishamhm as the committer. I wonder what they have to say about it.

**Comment by hishamhm** [comment] 2019-08-11 15:13
Can you try the lastest code in git master?

I believe this is now fixed. If so, I will push a new release shortly.

>

**Comment by doronbehar** [comment] 2019-08-11 15:21
Sorry for not posting again but I've worked around this issue in my own rocks by using `git://` `source.url` and not `https://...tar.gz`. I'm not sure I can reproduce this now as the changes were committed in my repositories with `--amend` and pushed with `--force`.

Maybe @MisterDA can try the latest git master.

**Comment by MisterDA** [comment] 2019-08-11 17:29
The error has slightly changed.
I installed luarocks from master with `./configure && make && sudo make install`. The local tree was purged. Dependencies were installed without problems.
My [rockspec is here](https://github.com/MisterDA/love-release/blob/master/rockspecs/love-release-2.0.13-1.rockspec).

```
$ luarocks install --local love-release
Installing https://luarocks.org/love-release-2.0.13-1.rockspec

Cloning into 'love-release'...
remote: Enumerating objects: 27, done.
remote: Counting objects: 100% (27/27), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 27 (delta 2), reused 10 (delta 0), pack-reused 0
Receiving objects: 100% (27/27), 16.84 KiB | 5.61 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Note: checking out 'fef178e5924665ca3edf34cb671ed7fa5fa4a2e8'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

cp: cannot stat 'src/scripts/macosx.lua': No such file or directory

Error: Build error: Failed installing src/scripts/macosx.lua in /home/user/Projects/luarocks/./lua_modules/lib/luarocks/rocks-5.3/love-release/2.0.13-1/lua/love-release/scripts/macosx.lua: Failed copying src/scripts/macosx.lua to /home/user/Projects/luarocks/./lua_modules/lib/luarocks/rocks-5.3/love-release/2.0.13-1/lua/love-release/scripts/macosx.lua
```

**Comment by hishamhm** [comment] 2019-08-11 23:17
@MisterDA that's because the rockspec is incorrect: the file is called
src/scripts/macos.lua (without the "x") in your repo. :)

>

**Comment by MisterDA** [comment] 2019-08-12 09:52
@hishamhm thank you very much! I did not inspect the error message carefully enough…
I confirm that LuaRocks master fixes the bug for me.

**Closed** 2019-08-13 09:34 UTC
