### ISSUE TITLE
The command syntax is incorrect

### ISSUE THREAD

**Issue by Nazadup** [luarocks/luarocks#1233] opened 2020-10-13 21:43 UTC
So i'm trying to install Luarocks in a Windows 10, and i did it multiple times using multiple methods but whenever i try the command: luarocks , i get that answer from the prompt: The command syntax is incorrect. I've tried the command on cmd, PowerShell, Visual Studio and Visual Studio Code, with all of them giving the same response. The directory path seems to be correct because when i get it wrong the prompts shows another error.

My Windows is in portuguese, but i'll post some prints anyway.
![luarockspowershell](https://user-images.githubusercontent.com/72818938/95919470-04110300-0d84-11eb-9421-ac5b55560072.PNG)
![luarocksstudiocode](https://user-images.githubusercontent.com/72818938/95919475-05dac680-0d84-11eb-837b-cb27ea194012.PNG)

**Comment by Tieske** [comment] 2020-10-13 22:01
If you want to try Lua on Windows, you could try [luawinmulti](https://github.com/tieske/luawinmulti) or [hererocks](https://github.com/luarocks/hererocks)

**Comment by hishamhm** [comment] 2020-10-13 22:04
Is this the same as #1232 ?

**Comment by Nazadup** [comment] 2020-10-13 22:17
> Is this the same as #1232 ?

I'm very new into programming, but it seems to be the same. I'm not sure tho.

**Comment by Nazadup** [comment] 2020-10-13 22:19
> If you want to try Lua on Windows, you could try [luawinmulti](https://github.com/tieske/luawinmulti) or [hererocks](https://github.com/luarocks/hererocks)

Thanks a lot, i'll give it a try right away. Do you think it's ok to a newbie in Lua use it on Windows, or do you think it would be easier for me to try it on Linux?

**Comment by devrrior** [comment] 2020-10-13 22:27
I have the same problem, when I type "luarocks" in cmd, it returns "The command syntax is incorrect". I need laurock for a neovim plugin. I dont know what to do. 
![image](https://user-images.githubusercontent.com/69869135/95922626-4c76f380-0d79-11eb-8c17-b5d4559f88ed.png)

**Comment by dirkstff** [comment] 2020-10-14 08:50
> 
> 
> Is this the same as #1232 ?

We would have to assume so. Symptoms are identical. And #1232 will hit mostly inexperienced users, because the more experienced ones will have some compiler installed, so that `vars.COMPILER_ENV_CMD != ""`.

**Comment by dirkstff** [comment] 2020-10-14 10:26
> 
> 
> I dont know what to do.

As a quick fix you can in luarocks.bat (and luarocks-admin.bat) delete the line ` >NUL`. This should be the third or so line. install.bat will of course always rewrite this when you do a new install.

**Comment by Nazadup** [comment] 2020-10-15 16:48
> > I dont know what to do.
> 
> As a quick fix you can in luarocks.bat (and luarocks-admin.bat) delete the line ` >NUL`. This should be the third or so line. install.bat will of course always rewrite this when you do a new install.

Cool. It worked, thank you very much!

**Comment by wesleywerner** [comment] 2020-10-17 21:56
I can confirm this happens with self contained installations too. Removing the NUL redirect fixes the issue temporarily.

For reference, I used the legacy package `luarocks-3.4.0-win32.zip` and performed the installation with these arguments:

`install.bat /NOADMIN /L /P C:\tools\luarocks /SELFCONTAINED`

I ran this from the visual studio developer command prompt.

**Comment by Vloz** [comment] 2020-11-08 16:11
> > I dont know what to do.
> 
> As a quick fix you can in luarocks.bat (and luarocks-admin.bat) delete the line ` >NUL`. This should be the third or so line. install.bat will of course always rewrite this when you do a new install.

Same issue, this worked.

**Comment by hishamhm** [comment] 2020-12-10 16:27
This should be fixed in LuaRocks 3.5.0!

**Closed** 2020-12-10 16:27 UTC
