### ISSUE TITLE
Error: Failed setting permission exec for all

### ISSUE THREAD

**Issue by zDylant** [luarocks/luarocks#1367] opened 2021-11-07 03:00 UTC
- **Platform:**

Windows

- **LuaRocks version:**
3.7.0

- **Configuration file:**
https://gist.github.com/zDylant/b85576d70d7abacf11d11252b8be603a

- **LuaRocks output from when the issue occurred:**
https://gist.github.com/zDylant/4b9eaf2cfec0a11bd8dc55134efbdc6f

- **Description:**

I am trying to install a package using luarocks for the first time, but I am getting this error

I am running the cmd as administrator and the same thing keeps happening

how can i fix it?

**Comment by hishamhm** [comment] 2021-11-08 10:13
Thank you for reporting! This a duplicate of #1312, and will be fixed in the next release.

**Closed by hishamhm** 2021-11-08 10:13 UTC
Labels: bug
