### ISSUE TITLE
I can't install package

### ISSUE THREAD

**Issue by falcon56321** [luarocks/luarocks#1500] opened 2023-04-06 13:51 UTC
### Please fill out the following:
- **Platform:** Linux/Ubuntu

- **LuaRocks version:** `3.9.2`

- **Configuration file:** default

- **LuaRocks output from when the issue occurred:**
  root@ati:~# sudo luarocks install luacrypto

Error: LuaRocks 3.9.2 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
        [C]: in function 'socket.http.request'
        /usr/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:739: in upvalue 'request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:847: in upvalue 'http_request'
        /usr/local/share/lua/5.4/luarocks/fs/lua.lua:914: in function 'luarocks.fs.lua.download'
        (...tail calls...)
        /usr/local/share/lua/5.4/luarocks/fetch.lua:154: in function 'luarocks.fetch.fetch_url'
        /usr/local/share/lua/5.4/luarocks/fetch.lua:50: in function 'luarocks.fetch.fetch_caching'
        /usr/local/share/lua/5.4/luarocks/manif.lua:108: in function 'luarocks.manif.load_manifest'
        /usr/local/share/lua/5.4/luarocks/search.lua:111: in function </usr/local/share/lua/5.4/luarocks/search.lua:101>
        (...tail calls...)
        /usr/local/share/lua/5.4/luarocks/search.lua:155: in function 'luarocks.search.search_repos'
        /usr/local/share/lua/5.4/luarocks/search.lua:241: in function 'luarocks.search.find_suitable_rock'
        /usr/local/share/lua/5.4/luarocks/search.lua:263: in function 'luarocks.search.find_rock_checking_lua_versions'
        /usr/local/share/lua/5.4/luarocks/cmd/install.lua:246: in function 'luarocks.cmd.install.command'
        (...tail calls...)
        [C]: in function 'xpcall'
        /usr/local/share/lua/5.4/luarocks/cmd.lua:672: in function 'luarocks.cmd.run_command'
        /usr/local/bin/luarocks:38: in main chunk
        [C]: in ?
root@ati:~# luarocks --verbose
fs.current_dir()
fs.quiet_stderr("pwd")

io.popen:       pwd 2> /dev/null
fs.current_dir()
fs.is_superuser()
fs.current_user()
fs.system_cache_dir()
fs.is_dir("/var/cache")
fs.absolute_name("/var/cache")
fs.current_dir()
fs.is_file("/usr/lib/liblua5.4.a")
fs.absolute_name("/usr/lib/liblua5.4.a")
fs.current_dir()
fs.is_dir("/usr/lib/liblua5.4.a")
fs.absolute_name("/usr/lib/liblua5.4.a")
fs.current_dir()
fs.is_file("/usr/lib/x86_64-linux-gnu/liblua5.4.a")
fs.absolute_name("/usr/lib/x86_64-linux-gnu/liblua5.4.a")
fs.current_dir()
fs.is_dir("/usr/lib/x86_64-linux-gnu/liblua5.4.a")
fs.absolute_name("/usr/lib/x86_64-linux-gnu/liblua5.4.a")
fs.current_dir()
fs.exists("/usr/bin")
fs.absolute_name("/usr/bin")
fs.current_dir()
fs.exists("/usr")
fs.absolute_name("/usr")
fs.current_dir()
fs.exists("/usr/bin/lua5.4")
fs.absolute_name("/usr/bin/lua5.4")
fs.current_dir()
fs.absolute_name("/usr/local/etc/luarocks/config-5.4.lua")
fs.current_dir()
fs.absolute_name("/root/.luarocks/config-5.4.lua")
fs.current_dir()
fs.absolute_name("/root/.luarocks")
fs.current_dir()
fs.absolute_name("/usr/local")
fs.current_dir()

- **Description:**
 I deleted lua and everything about luarocks and restored it again. I couldn't solve my problem, can you help me please

**Comment by clitic** [comment] 2023-05-01 08:33
@falcon56321 I think luasec (or luasocket) library is corrupted somehow. Re-install luasec (or luasocket) and then try to install luacrypto/luaossl.

**Comment by hishamhm** [comment] 2024-02-17 04:47
This is a duplicate of #1422. See more info here: https://github.com/luarocks/luarocks/issues/1422#issuecomment-1172649206

**Closed by hishamhm** 2024-02-17 04:47 UTC
