### ISSUE TITLE
I'm unable to install anything with luarocks

### ISSUE THREAD

**Issue by 1337M0nst3r** [luarocks/luarocks#1008] opened 2019-05-06 17:12 UTC
I installed luarocks today from the Arch Linux repository.
When I tried to install argparse, I got the following error:
Error: Your user does not have write permissions in /usr/lib/luarocks/rocks-5.3 
-- you may want to run as a privileged user or use your local tree with --local.

So I runned it with sudo and I got the following:
/usr/bin/lua5.3: /usr/share/lua/5.3/luarocks/core/dir.lua:21: invalid value (boolean) at index 1 in table for 'concat'
stack traceback:
	[C]: in function 'table.concat'
	/usr/share/lua/5.3/luarocks/core/dir.lua:21: in function 'luarocks.dir.path'
	/usr/share/lua/5.3/luarocks/cmd.lua:160: in upvalue 'get_lua_version'
	/usr/share/lua/5.3/luarocks/cmd.lua:287: in function 'luarocks.cmd.run_command'
	/usr/bin/luarocks:38: in main chunk
	[C]: in ?
Then I tried installing using --local and it worked.
It seems like only when I use --local I can do anything with luarocks.
Installing packages or building them is throwing the same errors above.

My OS is Arch Linux x86_64 in case it helps.

**Comment by 1337M0nst3r** [comment] 2019-05-07 05:54
Using luarocks from Termux works fine though

**Comment by daurnimator** [comment] 2019-05-07 06:00
Duplicate of #1004

**Closed by daurnimator** 2019-05-07 06:00 UTC

**Comment by 1337M0nst3r** [comment] 2019-05-07 18:04
I see, thank you.
