### ISSUE TITLE
Invalid Debian Installation

### ISSUE THREAD

**Issue by a-ushakov31293** [luarocks/luarocks#1648] opened 2024-03-13 18:37 UTC
Hello.

Debian 12, x64.

After doing steps described here

```
https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix#quick-start
```

I have got unworkable `luarocks` installation checked by

```sh
luarocks install lapis
```

error message
```
workernode1 luarocks remove lua-sec
/usr/local/bin/lua: /usr/local/share/lua/5.3/luarocks/cmd.lua:738: attempt to concatenate a table value (field 'root_dir')
stack traceback:
	/usr/local/share/lua/5.3/luarocks/cmd.lua:738: in function 'luarocks.cmd.run_command'
	/usr/local/bin/luarocks:38: in main chunk
	[C]: in ?
```

What can cause an error?

**Comment by hishamhm** [comment] 2024-03-13 19:01
This is a duplicate of #1626 — a new release with the fix is coming shortly!

**Closed by hishamhm** 2024-03-13 19:01 UTC
