### ISSUE TITLE
how to change cmake build type library install path

### ISSUE THREAD

**Issue by zhanlangorz** [luarocks/luarocks#1439] opened 2022-09-07 04:27 UTC
When i write a rockspec for librdkafka, like this:

```
package = "librdkafka"
version = "1.9.2-1"
source = { 
   url ="xxx",
}
description = { 
   summary = "librdkafka for luarocks",
   detailed = "", 
   homepage = "https://github.com/edenhill/librdkafka",
}
dependencies = { 
   "lua >= 5.1"
}
build = { 
   type = "cmake",
   variables = { 
     CMAKE_BUILD_TYPE = "Release",
     CMAKE_INSTALL_LIBDIR = "$(PREFIX)",
     CMAKE_INSTALL_BINDIR = "$(PREFIX)",
     CMAKE_INSTALL_INCLUDEDIR = "$(PREFIX)",
   },  
}
```
Then i install this rock use --tree option:
luarocks install librdkafka-1.9.2-1.src.rock --tree=./luarocks_mod

this rock will install to luarocks_mod/lib/luarocks/rocks-5.1/librdkafka/1.9.2-1/, i can't require this library without the full path.

how to change my rockspec to install the compilerd shared library to [--treepath]/lib/ ?

**Comment by alerque** [comment] 2022-09-07 07:54
Duplicate of #1438.

**Comment by zhanlangorz** [comment] 2022-09-07 07:54
已收到!

**Closed** 2022-09-07 22:39 UTC
Labels: enhancement

**Comment by zhanlangorz** [comment] 2022-10-11 08:10
已收到!
