### ISSUE TITLE
Error: LuaRocks 3.7.0 bug (please report ...)

### ISSUE THREAD

**Issue by klankschap** [luarocks/luarocks#1316] opened 2021-06-23 13:46 UTC
No clue as what is going on. Just following the request to report.

$ luarocks search inifile

Error: LuaRocks 3.7.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/home/vm/.luarocks/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
	[C]: in function 'socket.http.request'
	/home/vm/.luarocks/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:729: in upvalue 'request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:827: in upvalue 'http_request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:904: in function 'luarocks.fs.lua.download'
	(...tail calls...)
	/usr/local/share/lua/5.4/luarocks/fetch.lua:154: in function 'luarocks.fetch.fetch_url'
	/usr/local/share/lua/5.4/luarocks/fetch.lua:50: in function 'luarocks.fetch.fetch_caching'
	/usr/local/share/lua/5.4/luarocks/manif.lua:108: in function 'luarocks.manif.load_manifest'
	/usr/local/share/lua/5.4/luarocks/search.lua:111: in function </usr/local/share/lua/5.4/luarocks/search.lua:101>
	(...tail calls...)
	/usr/local/share/lua/5.4/luarocks/search.lua:155: in function 'luarocks.search.search_repos'
	/usr/local/share/lua/5.4/luarocks/cmd/search.lua:68: in function 'luarocks.cmd.search.command'
	(...tail calls...)
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.4/luarocks/cmd.lua:663: in function 'luarocks.cmd.run_command'
	/usr/local/bin/luarocks:38: in main chunk
	[C]: in ?
Exit status: 99 [15:36] vm @ vmz: ~/Downloads/luarocks/luarocks-3.7.0 
$ luarocks search inifile --verbose
Defaulting to Lua 5.4 based on ./.luarocks/default-lua-version.lua ...
fs.current_dir()
fs.current_dir()
fs.is_superuser()
fs.make_dir("/home/vm/.cache/luarocks/https___luarocks.org")
fs.execute("mkdir -p", "/home/vm/.cache/luarocks/https___luarocks.org")
fs.Q("/home/vm/.cache/luarocks/https___luarocks.org")
fs.execute_string("mkdir -p '/home/vm/.cache/luarocks/https___luarocks.org'")
fs.current_dir()
fs.command_at("/home/vm/Downloads/luarocks/luarocks-3.7.0", "mkdir -p '/home/vm/.cache/luarocks/https___luarocks.org'")
fs.absolute_name("/home/vm/Downloads/luarocks/luarocks-3.7.0")
fs.current_dir()
fs.Q("/home/vm/Downloads/luarocks/luarocks-3.7.0")

os.execute: 	cd '/home/vm/Downloads/luarocks/luarocks-3.7.0' && mkdir -p '/home/vm/.cache/luarocks/https___luarocks.org'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0
fs.download("https://luarocks.org/manifest-5.4.zip", "/home/vm/.cache/luarocks/https___luarocks.org/manifest-5.4.zip", true)
fs.absolute_name("/home/vm/.cache/luarocks/https___luarocks.org/manifest-5.4.zip")
fs.current_dir()
HEAD	https://luarocks.org/manifest-5.4.zip

Error: LuaRocks 3.7.0 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/home/vm/.luarocks/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
	[C]: in function 'socket.http.request'
	/home/vm/.luarocks/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:729: in upvalue 'request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:827: in upvalue 'http_request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:904: in function 'luarocks.fs.lua.download'
	(...tail calls...)
	/usr/local/share/lua/5.4/luarocks/fetch.lua:154: in function 'luarocks.fetch.fetch_url'
	/usr/local/share/lua/5.4/luarocks/fetch.lua:50: in function 'luarocks.fetch.fetch_caching'
	/usr/local/share/lua/5.4/luarocks/manif.lua:108: in function 'luarocks.manif.load_manifest'
	/usr/local/share/lua/5.4/luarocks/search.lua:111: in function </usr/local/share/lua/5.4/luarocks/search.lua:101>
	(...tail calls...)
	/usr/local/share/lua/5.4/luarocks/search.lua:155: in function 'luarocks.search.search_repos'
	/usr/local/share/lua/5.4/luarocks/cmd/search.lua:68: in function 'luarocks.cmd.search.command'
	(...tail calls...)
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.4/luarocks/cmd.lua:663: in function 'luarocks.cmd.run_command'
	/usr/local/bin/luarocks:38: in main chunk
	[C]: in ?
fs.change_dir_to_root()
fs.current_dir()
fs.is_dir("/home/vm/Downloads/luarocks/luarocks-3.7.0")
fs.absolute_name("/home/vm/Downloads/luarocks/luarocks-3.7.0")
fs.current_dir()

**Comment by daurnimator** [comment] 2021-06-23 14:06
Duplicate of  https://github.com/luarocks/luarocks/issues/1302 / https://github.com/brunoos/luasec/issues/171

**Closed by daurnimator** 2021-06-23 14:06 UTC
Labels: bug
