### ISSUE TITLE
please report at https://github.com/luarocks/luarocks/issues

### ISSUE THREAD

**Issue by ClaudioGi** [luarocks/luarocks#1528] opened 2023-08-16 15:26 UTC
### Please fill out the following:
- **Platform:**
  - Linux
  -  **LuaRocks 3.9.2**
  **Configuration file:**
- **LuaRocks output from when the issue occurred:**
  - Use the `--verbose` flag.

~ $ sudo /usr/local/bin/luarocks install ffi --verbose
fs.current_dir()
fs.quiet_stderr("pwd")

io.popen: 	pwd 2> /dev/null
fs.current_dir()
fs.is_superuser()
fs.current_user()
fs.system_cache_dir()
fs.is_dir("/var/cache")
fs.absolute_name("/var/cache")
fs.current_dir()
fs.check_command_permissions(table: 0x5632a6853920)
fs.exists("/usr/local/lib/luarocks/rocks-5.4")
fs.absolute_name("/usr/local/lib/luarocks/rocks-5.4")
fs.current_dir()
fs.root_of("/usr/local/lib/luarocks/rocks-5.4")
fs.exists("/usr/local/lib/luarocks")
fs.absolute_name("/usr/local/lib/luarocks")
fs.current_dir()
fs.exists("/usr/local/lib")
fs.absolute_name("/usr/local/lib")
fs.current_dir()
fs.is_writable("/usr/local/lib")
fs.is_dir("/usr/local/lib")
fs.absolute_name("/usr/local/lib")
fs.current_dir()
fs.exists("/usr/local/share/lua/5.4")
fs.absolute_name("/usr/local/share/lua/5.4")
fs.current_dir()
fs.is_writable("/usr/local/share/lua/5.4")
fs.is_dir("/usr/local/share/lua/5.4")
fs.absolute_name("/usr/local/share/lua/5.4")
fs.current_dir()
fs.exists("/usr/local/bin")
fs.absolute_name("/usr/local/bin")
fs.current_dir()
fs.is_writable("/usr/local/bin")
fs.is_dir("/usr/local/bin")
fs.absolute_name("/usr/local/bin")
fs.current_dir()
fs.exists("/usr/local/share/lua/5.4")
fs.absolute_name("/usr/local/share/lua/5.4")
fs.current_dir()
fs.is_writable("/usr/local/share/lua/5.4")
fs.is_dir("/usr/local/share/lua/5.4")
fs.absolute_name("/usr/local/share/lua/5.4")
fs.current_dir()
fs.make_dir("/var/cache/luarocks/https___luarocks.org")
fs.execute("mkdir -p", "/var/cache/luarocks/https___luarocks.org")
fs.Q("/var/cache/luarocks/https___luarocks.org")
fs.execute_string("mkdir -p '/var/cache/luarocks/https___luarocks.org'")
fs.current_dir()
fs.command_at("/home/neo/Downloads", "mkdir -p '/var/cache/luarocks/https___luarocks.org'")
fs.absolute_name("/home/neo/Downloads")
fs.current_dir()
fs.Q("/home/neo/Downloads")

os.execute: 	cd '/home/neo/Downloads' && mkdir -p '/var/cache/luarocks/https___luarocks.org'
Results: 3
  1 (boolean): true
  2 (string): exit
  3 (number): 0
fs.download("https://luarocks.org/manifest-5.4.zip", "/var/cache/luarocks/https___luarocks.org/manifest-5.4.zip", true)
fs.absolute_name("/var/cache/luarocks/https___luarocks.org/manifest-5.4.zip")
fs.current_dir()
GET	https://luarocks.org/manifest-5.4.zip

Error: LuaRocks 3.9.2 bug (please report at https://github.com/luarocks/luarocks/issues).
Arch.: linux-x86_64
/usr/share/lua/5.4/ssl/https.lua:66: bad argument #2 to 'method' (string expected, got light userdata)
stack traceback:
	[C]: in function 'socket.http.request'
	/usr/share/lua/5.4/ssl/https.lua:132: in function 'ssl.https.request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:739: in upvalue 'request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:847: in upvalue 'http_request'
	/usr/local/share/lua/5.4/luarocks/fs/lua.lua:914: in function 'luarocks.fs.lua.download'
	(...tail calls...)
	/usr/local/share/lua/5.4/luarocks/fetch.lua:154: in function 'luarocks.fetch.fetch_url'
	/usr/local/share/lua/5.4/luarocks/fetch.lua:50: in function 'luarocks.fetch.fetch_caching'
	/usr/local/share/lua/5.4/luarocks/manif.lua:108: in function 'luarocks.manif.load_manifest'
	/usr/local/share/lua/5.4/luarocks/search.lua:111: in function </usr/local/share/lua/5.4/luarocks/search.lua:101>
	(...tail calls...)
	/usr/local/share/lua/5.4/luarocks/search.lua:155: in function 'luarocks.search.search_repos'
	/usr/local/share/lua/5.4/luarocks/search.lua:241: in function 'luarocks.search.find_suitable_rock'
	/usr/local/share/lua/5.4/luarocks/search.lua:263: in function 'luarocks.search.find_rock_checking_lua_versions'
	/usr/local/share/lua/5.4/luarocks/cmd/install.lua:246: in function 'luarocks.cmd.install.command'
	(...tail calls...)
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.4/luarocks/cmd.lua:672: in function 'luarocks.cmd.run_command'
	/usr/local/bin/luarocks:38: in main chunk
	[C]: in ?
fs.change_dir_to_root()
fs.current_dir()
fs.is_dir("/home/neo/Downloads")
fs.absolute_name("/home/neo/Downloads")
fs.c

**Comment by hishamhm** [comment] 2024-02-17 02:15
This is a duplicate of #1422. See more info here: https://github.com/luarocks/luarocks/issues/1422#issuecomment-1172649206

**Closed by hishamhm** 2024-02-17 02:15 UTC
