### ISSUE TITLE
Error: LuaRocks 2.4.1 bug (please report at https://github.com/keplerproject/luarocks/issues).

### ISSUE THREAD

**Issue by misschuer** [luarocks/luarocks#805] opened 2018-05-30 08:41 UTC
Error: LuaRocks 2.4.1 bug (please report at https://github.com/keplerproject/luarocks/issues).
...local/openresty/luajit/share/lua/5.1/luarocks/fs/lua.lua:734: attempt to call field 'sumhexa' (a nil value)
stack traceback:
	...local/openresty/luajit/share/lua/5.1/luarocks/fs/lua.lua:734: in function 'get_md5'
	.../local/openresty/luajit/share/lua/5.1/luarocks/manif.lua:76: in function 'make_rock_manifest'
	.../local/openresty/luajit/share/lua/5.1/luarocks/build.lua:320: in function 'build_rockspec'
	.../local/openresty/luajit/share/lua/5.1/luarocks/build.lua:365: in function 'do_build'
	.../local/openresty/luajit/share/lua/5.1/luarocks/build.lua:407: in function <.../local/openresty/luajit/share/lua/5.1/luarocks/build.lua:396>
	[C]: in function 'xpcall'
	...openresty/luajit/share/lua/5.1/luarocks/command_line.lua:180: in function 'run_command'
	/usr/bin/luarocks:34: in main chunk
	[C]: at 0x004051d0

**Comment by daurnimator** [comment] 2018-05-31 00:05
Duplicate of #627, #550, #500, and #494.

However, it should have been fixed in >=2.4.0.
Do you have some other 'md5' module installed that could be interfering?

**Closed** 2018-06-13 02:06 UTC
