### ISSUE TITLE
Cannot find -lmysqlclient 

### ISSUE THREAD

**Issue by jmosele0** [luarocks/luarocks#1089] opened 2019-09-11 07:19 UTC
So I've been trying to install luasql-mysql with luarocks but I keep getting an error that it can't find -lmysqlclient.

Here's the command I gave for luarocks:

luarocks install luasql-mysql MYSQL_INCDIR=C:\Users\jack\AppData\Roaming\LuaRocks

And this was the output I got:

A required privilege is not held by the client.
Warning: Could not find a Lua 5.1 interpreter in your PATH. Modules may not install with the correct configurations. You may want to specify the path prefix to your build of Lua 5.1 using --lua-dir
A required privilege is not held by the client.
Installing https://luarocks.org/luasql-mysql-2.5.0-1.rockspec

Cloning into 'luasql'...
remote: Enumerating objects: 142, done.
remote: Counting objects: 100% (142/142), done.
remote: Compressing objects: 100% (99/99), done.
Receiving objects:  97% (138/142)    68 (delta 29), pack-reused 0 eceiving objects:  86% (123/142)
Receiving objects: 100% (142/142), 102.51 KiB | 274.00 KiB/s, done.
Resolving deltas: 100% (64/64), done.
Note: checking out '5496d60185db0c4578e8abe0c74343e99b799311'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

mingw32-gcc -O2 -c -o src/luasql.o -IC:\Program Files (x86)\Lua\5.1\include src/luasql.c -IC:\Users\jack\AppData\Roaming\LuaRocks
mingw32-gcc -O2 -c -o src/ls_mysql.o -IC:\Program Files (x86)\Lua\5.1\include src/ls_mysql.c -IC:\Users\jack\AppData\Roaming\LuaRocks
mingw32-gcc -shared -o luasql/mysql.dll src/luasql.o src/ls_mysql.o -Lc:/external -lmysqlclient C:\Program Files (x86)\Lua\5.1/lua5.1.dll -lMSVCR80
c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe: cannot find -lmysqlclient
collect2.exe: error: ld returned 1 exit status

Error: Build error: Failed compiling module luasql/mysql.dll

I've made sure I have the file on my computer. I'm really not sure why this error is occurring.

**Comment by tomasguisasola** [comment] 2019-09-11 10:05
Hi jmosele0

I have never used mingw, but I would try to provide the path to the
libraries.  With gcc we use -L<path> and then -lfoo will tell the
link-editor to search for <path>/libfoo.so (on a unix SO, where library
files start with 'lib' prefix and ends with '.so' extension).

Regards,
Tomás

Em qua, 11 de set de 2019 às 04:19, jmosele0 <notifications@github.com>
escreveu:
>
> So I've been trying to install luasql-mysql with luarocks but I keep
getting an error that it can't find -lmysqlclient.
>
> Here's the command I gave for luarocks:
>
> luarocks install luasql-mysql
MYSQL_INCDIR=C:\Users\jack\AppData\Roaming\LuaRocks
>
> And this was the output I got:
>
> A required privilege is not held by the client.
> Warning: Could not find a Lua 5.1 interpreter in your PATH. Modules may
not install with the correct configurations. You may want to specify the
path prefix to your build of Lua 5.1 using --lua-dir
> A required privilege is not held by the client.
> Installing https://luarocks.org/luasql-mysql-2.5.0-1.rockspec
>
> Cloning into 'luasql'...
> remote: Enumerating objects: 142, done.
> remote: Counting objects: 100% (142/142), done.
> remote: Compressing objects: 100% (99/99), done.
> Receiving objects: 97% (138/142) 68 (delta 29), pack-reused 0 eceiving
objects: 86% (123/142)
> Receiving objects: 100% (142/142), 102.51 KiB | 274.00 KiB/s, done.
> Resolving deltas: 100% (64/64), done.
> Note: checking out '5496d60185db0c4578e8abe0c74343e99b799311'.
>
> You are in 'detached HEAD' state. You can look around, make experimental
> changes and commit them, and you can discard any commits you make in this
> state without impacting any branches by performing another checkout.
>
> If you want to create a new branch to retain commits you create, you may
> do so (now or later) by using -b with the checkout command again. Example:
>
> git checkout -b
>
> mingw32-gcc -O2 -c -o src/luasql.o -IC:\Program Files
(x86)\Lua\5.1\include src/luasql.c -IC:\Users\jack\AppData\Roaming\LuaRocks
> mingw32-gcc -O2 -c -o src/ls_mysql.o -IC:\Program Files
(x86)\Lua\5.1\include src/ls_mysql.c
-IC:\Users\jack\AppData\Roaming\LuaRocks
> mingw32-gcc -shared -o luasql/mysql.dll src/luasql.o src/ls_mysql.o
-Lc:/external -lmysqlclient C:\Program Files (x86)\Lua\5.1/lua5.1.dll
-lMSVCR80
> c:/mingw/bin/../lib/gcc/mingw32/8.2.0/../../../../mingw32/bin/ld.exe:
cannot find -lmysqlclient
> collect2.exe: error: ld returned 1 exit status
>
> Error: Build error: Failed compiling module luasql/mysql.dll
>
> I've made sure I have the file on my computer. I'm really not sure why
this error is occurring.

**Comment by hishamhm** [comment] 2019-09-23 17:26
> luarocks install luasql-mysql MYSQL_INCDIR=C:\Users\jack\AppData\Roaming\LuaRocks

Try passing also MYSQL_LIBDIR, giving it the directory where `luasql/mysql.dll` is contained.

**Comment by hishamhm** [comment] 2020-02-13 17:00
Closing this since it is not a reproducible LuaRocks bug

**Closed by hishamhm** 2020-02-13 17:00 UTC
