### ISSUE TITLE
Traceback from luarocks 3 make inside of rocks_dir

### ISSUE THREAD

**Issue by daurnimator** [luarocks/luarocks#891] opened 2018-08-12 16:44 UTC
```
$ sudo luarocks make
lua: /usr/share/lua/5.3/luarocks/core/path.lua:17: assertion failed!
stack traceback:
	[C]: in function 'assert'
	/usr/share/lua/5.3/luarocks/core/path.lua:17: in function 'luarocks.core.path.rocks_dir'
	/usr/share/lua/5.3/luarocks/path.lua:216: in function 'luarocks.path.use_tree'
	/usr/share/lua/5.3/luarocks/cmd.lua:224: in upvalue 'process_tree_flags'
	/usr/share/lua/5.3/luarocks/cmd.lua:425: in function 'luarocks.cmd.run_command'
	/usr/bin/luarocks:38: in main chunk
	[C]: in ?
```

**Comment by hishamhm** [comment] 2018-08-12 18:27
line 425 in /usr/share/lua/5.3/luarocks/cmd.lua in 3.0.1-rc1 is not calling process_tree_flags. Looks like you've got mixed installations?

**Comment by hishamhm** [comment] 2018-08-12 18:48
Do you have steps to reproduce it on a build of the vanilla tarball?

**Comment by daurnimator** [comment] 2018-08-13 03:36
Hrm, looks like it was on that line before f893acf2409bb4ec8a4669a9e4380a98737c6b40 was commited. I thought I had 3.0.1-rc1 installed but perhaps it was only 3.0.0.
Do you think the issue has been fixed since? Or just moved to a different location?

**Comment by hishamhm** [comment] 2018-08-14 16:07
> Do you think the issue has been fixed since? Or just moved to a different location?

Hard to say since I tried but couldn't reproduce. Closing this for now. Feel free to reopen if it reappears.

**Closed by hishamhm** 2018-08-14 16:07 UTC
