### ISSUE TITLE
luarocks "dev bug" No LuaRocks module found for luarocks.test

### ISSUE THREAD

**Issue by dcurrie** [luarocks/luarocks#917] opened 2018-09-16 22:24 UTC
e$ luarocks

LuaRocks dev, the Lua package manager

NAME
	/usr/local/bin/luarocks - LuaRocks main command-line interface

SYNOPSIS
	/usr/local/bin/luarocks [<flags...>] [VAR=VALUE]... <command> [<argument>] 

GENERAL OPTIONS
	These apply to all commands, as appropriate:

	--dev                  Enable the sub-repositories in rocks servers
	                       for rockspecs of in-development versions
	--server=<server>      Fetch rocks/rockspecs from this server
	                       (takes priority over config file)
	--only-server=<server> Fetch rocks/rockspecs from this server only
	                       (overrides any entries in the config file)
	--only-sources=<url>   Restrict downloads to paths matching the
	                       given URL.
	--tree=<tree>          Which tree to operate on.
	--local                Use the tree in the user's home directory.
	                       To enable it, see '/usr/local/bin/luarocks help path'.
	--verbose              Display verbose output of commands executed.
	--timeout=<seconds>    Timeout on network operations, in seconds.
	                       0 means no timeout (wait forever).
	                       Default is 30.

VARIABLES
	Variables from the "variables" table of the configuration file
	can be overriden with VAR=VALUE assignments.

COMMANDS
	build
		build/compile a rock.
	config
		Query information about the LuaRocks configuration.
	doc
		Show documentation for an installed rock.
	download
		Download a specific rock file from a rocks server.
	help
		Help on commands. Type '/usr/local/bin/luarocks help <command>' for more.
	init
		Initialize a directory for a Lua project using LuaRocks.
	install
		Install a rock.
	lint
		Check syntax of a rockspec.
	list
		List currently installed rocks.
	make
		Compile package in current directory using a rockspec.
	new_version
		Auto-write a rockspec for a new version of a rock.
	pack
		Create a rock, packing sources or binaries.
	path
		Return the currently configured package path.
	purge
		Remove all installed rocks from a tree.
	remove
		Uninstall a rock.
	search
		Query the LuaRocks servers.
	show
		Show information about an installed rock.

Error: LuaRocks dev bug (please report at https://github.com/luarocks/luarocks/issues).
/usr/local/share/lua/5.4/luarocks/cmd/test.lua:7: module 'luarocks.test' not found:No LuaRocks module found for luarocks.test
	no field package.preload['luarocks.test']
	no file '/usr/local/share/lua/5.4/luarocks/test.lua'
	no file '/usr/local/share/lua/5.4/luarocks/test/init.lua'
	no file '/usr/local/lib/lua/5.4/luarocks/test.lua'
	no file '/usr/local/lib/lua/5.4/luarocks/test/init.lua'
	no file './luarocks/test.lua'
	no file './luarocks/test/init.lua'
	no file '/Users/e/.luarocks/share/lua/5.4/luarocks/test.lua'
	no file '/Users/e/.luarocks/share/lua/5.4/luarocks/test/init.lua'
	no file '/usr/local/lib/lua/5.4/luarocks/test.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './luarocks/test.so'
	no file '/Users/e/.luarocks/lib/lua/5.4/luarocks/test.so'
	no file '/usr/local/lib/lua/5.4/luarocks.so'
	no file '/usr/local/lib/lua/5.4/loadall.so'
	no file './luarocks.so'
	no file '/Users/e/.luarocks/lib/lua/5.4/luarocks.so'
stack traceback:
	[C]: in function 'require'
	/usr/local/share/lua/5.4/luarocks/cmd/test.lua:7: in main chunk
	[C]: in function 'require'
	/usr/local/share/lua/5.4/luarocks/cmd/help.lua:75: in function 'luarocks.cmd.help.command'
	(...tail calls...)
	[C]: in function 'xpcall'
	/usr/local/share/lua/5.4/luarocks/command_line.lua:240: in function 'luarocks.command_line.run_command'
	/usr/local/bin/luarocks:37: in main chunk
	[C]: in ?
e$

**Comment by hishamhm** [comment] 2018-09-16 22:36
@dcurrie Thanks for reporting! How did you install it? `make` or `make bootstrap`? Is this running the latest commit from `master`?

**Comment by dcurrie** [comment] 2018-09-16 22:53
@hishamhm I don't remember how I installed... sorry. Install date was Jun 30. I believe I just followed the instructions on https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Unix

I just tried to update using:

e$ luarocks install luarocks
Installing https://luarocks.org/luarocks-3.0.3-1.src.rock

Error: /var/folders/47/v0msmb354ng3j1y51snkj0km0000gn/T//luarocks_luarocks-3.0.3-1-NCKl2b/luarocks-3.0.3-1.rockspec: Unknown field unix (rockspec format 3.0)

but failed... :(

Strangely, unknown field flips between unix and windows (I'm on macOS)...

e$ luarocks install luarocks
Installing https://luarocks.org/luarocks-3.0.3-1.src.rock

Error: /var/folders/47/v0msmb354ng3j1y51snkj0km0000gn/T//luarocks_luarocks-3.0.3-1-9rFOm2/luarocks-3.0.3-1.rockspec: Unknown field windows (rockspec format 3.0)
algorithm e$

**Comment by hishamhm** [comment] 2018-09-19 19:59
Hard to debug from a previous dev version, sorry — there were intermediate commits in between 2.x and 3.0 where `luarocks install luarocks` was broken. I'm currently closing this one since it's not reproducible in the latest `master`.

But thank you for the feedback! Please continue to report any issues you get from a fresh install.

**Closed by hishamhm** 2018-09-19 19:59 UTC
