### ISSUE TITLE
Luarocks can't install library 

### ISSUE THREAD

**Issue by timotirta** [luarocks/luarocks#905] opened 2018-08-26 11:28 UTC
when i want to install nngraph using this 
`luarocks --from=https://raw.githubusercontent.com/torch/rocks/master/ install nngraph`
it said:
Error: Failed finding Lua library. You may need to configure LUA_LIBDIR.

my os : Windows 10

**Comment by HustLion** [comment] 2018-09-28 02:55
You can try reinstall luarocks. I suggest you use source code install as specified in [the wiki](https://github.com/luarocks/luarocks/wiki/Installation-instructions-for-Windows).

**Comment by Homedrew** [comment] 2019-02-21 19:27
I have the same issue building from source code. The config-5.3.lua does not include LUA_LIBDIR but even when added, it makes no difference.

**Comment by cup** [comment] 2019-03-08 23:38
https://github.com/luarocks/luarocks/issues/858

**Comment by andrewstarks** [comment] 2019-05-29 04:18
++1

`Error: Failed finding Lua library. You may need to configure LUA_LIBDIR.` on fresh install on Mac OSX.  It doesn't matter if I add it or not. Installing from homebrew works, but that's version 3.01.

**Comment by Bilal2453** [comment] 2020-04-24 01:03
Is there any workaround for this issue ?

as using `--lua-dir` and configuring `LUA_LIBDIR` makes no any difference
i have fresh install too.

**Comment by WywTed** [comment] 2020-04-25 12:26
when i am under the directory of kong , and exec "luarocks make"  it occured the same problem
os: win10 64
luarocks: 3.3.1
lua: 5.3
![image](https://user-images.githubusercontent.com/12699301/80279922-14301a00-8733-11ea-8ea8-6488e2b52d8f.png)

**Comment by Bilal2453** [comment] 2020-04-26 22:33
oh i found if you installed the latest luarocks (last commits, using git) not luarocks v3.3.1, you can force it to use `--lua-dir`  flag and point it to lua instillation which will solve this.

Still setting LUA_LIBDIR doesn't affect anything though.

**Comment by hishamhm** [comment] 2020-04-27 18:38
Glad to hear the latest master works better. How are you setting LUA_LIBDIR?

**Comment by hishamhm** [comment] 2020-04-27 18:40
@WywTed Kong does not work on Windows

**Comment by Bilal2453** [comment] 2020-04-29 11:18
> Glad to hear the latest master works better. How are you setting LUA_LIBDIR?

Thank you sir, and sorry for the late response.

I am adding `LUA_LIBDIR` to `config-5.1.lua`, at the `variables` table with the value of `[[C:\lua]]`.
![My Configs](https://user-images.githubusercontent.com/38175840/80589685-51dabe80-8a23-11ea-8a6b-abe501f83630.png)

I wasn't sure about the value i should assign to `LUA_LIBDIR`, so i have tried many values like
`C:\\lua\\lib` and `C:\\lua\\lib\\lua`, and as in the screenshot `C:\\lua`, but non of them worked.

But using `--lua-dir` flag while using `install` or `build` *(and etc)* has solved this for me.

**Comment by timotirta** [comment] 2020-04-30 04:22
Sorry for late response. i'd given up on Luarocks on windows back then.
I'd used linux (Ubuntu 18.04) and everything was smoothly run and i'd done my project.

**Comment by Bilal2453** [comment] 2020-04-30 06:05
> Sorry for late response. i'd given up on Luarocks on windows back then.
> I'd used linux (Ubuntu 18.04) and everything was smoothly run and i'd done my project.

Indeed, but there are many developers who are developing specifically for Windows, working on Linux to develop for Windows is kinda tough, many developers are facing this same situation.
and some libraries can be only found on LuaRocks.

**Comment by hishamhm** [comment] 2020-04-30 18:00
@Bilal2453 thank you for the feedback! using the latest `master`, could you post the output of running `luarocks` with no arguments? (especially the "Configuration" section at the bottom) Thank you!

**Comment by Bilal2453** [comment] 2020-04-30 18:31
@hishamhm Sure, these are the results (i am kinda surprised tbh), using the last master, last commit 13 days ago.

The current `LUA_LIBDIR` value is `C:\Lua`, declared in `config-5.1.lua` in `variables` table.
*Tried same test with the same results but changed it to C:\lua\lib, same results, path exists*

#Running `luarocks`
![image](https://user-images.githubusercontent.com/38175840/80745874-a2d4da80-8b29-11ea-9511-a23c94ed9c7a.png)

**Comment by Bilal2453** [comment] 2020-04-30 18:32
i can confirm that what ever is the value of `LUA_LIBDIR` it will always return `(not found)`
even when the path actually exists.
tried many paths, same results.

**Comment by hishamhm** [comment] 2020-04-30 18:37
Ok, we're getting closer. That `(not found)` does not refer to the folder existing or not, but rather if LuaRocks is able to find a Lua library inside it. Assuming C:\Lua is the correct value for the Lua libdir in your system: what are its current contents?

**Comment by Bilal2453** [comment] 2020-04-30 18:42
> we're getting closer. That (not found) does not refer to the folder existing or not, but rather if LuaRocks is able to find a Lua library inside it

oh good to know

> what are its current contents?

oh yeah i forget this one actually.

this is my `C:\lua`
![image](https://user-images.githubusercontent.com/38175840/80746876-3a86f880-8b2b-11ea-8b97-ed5de9eb6a99.png)

This is my `C:\lua\lib`
![image](https://user-images.githubusercontent.com/38175840/80746939-538fa980-8b2b-11ea-8925-a2564280ae66.png)

And here is all of my libs, `C:\lua\lib\lua`
![image](https://user-images.githubusercontent.com/38175840/80747049-79b54980-8b2b-11ea-9f38-eb54c85e6397.png)

**Comment by Bilal2453** [comment] 2020-04-30 19:13
Hope that this is actually the correct path i should be using. As i have tried many many paths, but none worked

**Comment by hishamhm** [comment] 2020-04-30 20:03
`c:\lua\lib` should be the correct value for LUA_LIBDIR in your case because it is the one that contains `liblua.dll.a`. If you set `variables.LUA_LIBDIR` to that in `c:\lua\luarocks\config-5.1.lua`, then `luarocks` still says `(not found)`?

**Comment by Bilal2453** [comment] 2020-04-30 20:25
yes, it keeps saying `(not found)` whatever is its value.

![image](https://user-images.githubusercontent.com/38175840/80754699-25649680-8b38-11ea-9d5f-0fb7577382ca.png)

![image](https://user-images.githubusercontent.com/38175840/80755647-e0d9fa80-8b39-11ea-8c06-2e056f3e9570.png)

**Comment by happanda** [comment] 2022-07-28 03:51
Hi. Sorry to bring this ancient issue up. I come across same problem.
This is the command:
`luarocks install lua-requests`
This is the output:
`Error: Failed finding Lua library. You may need to configure LUA_LIBDIR.`
I tried using `--lua-dir` command line argument, but that gave same error.
Luarocks version:
```
λ luarocks --version
luarocks 3.9.1
LuaRocks main command-line interface
```

Lua version:
```
λ lua -v
Lua 5.4.2  Copyright (C) 1994-2020 Lua.org, PUC-Rio
```

Both my Lua and Luarocks are installed with scoop package manager.
Here's how my Lua folder looks like.
![lua-dir](https://user-images.githubusercontent.com/1078456/181415366-d2a308be-9534-4077-8eaf-e59e67ccc723.png)

Here is Luarocks config file.
```lua_interpreter = "lua54.exe"
lua_version = "5.4"
lib_extension = "dll"
rocks_trees = {
   "C:/home/scoop/apps/luarocks/current/rocks"
}
variables = {
   LUA_BINDIR = "C:/home/scoop/apps/lua/current",
   LUA_LIBDIR = "C:/home/scoop/apps/lua/current",
   LUA_DIR = "C:/home/scoop/apps/lua/current",
}
```

Output of `luarocks config`:

```
Configuration:
   Lua:
      Version    : 5.4
      Interpreter: C:/home/scoop/apps/lua/current/lua54.exe (ok)
      LUA_DIR    : C:/home/scoop/apps/lua/current (ok)
      LUA_BINDIR : C:/home/scoop/apps/lua/current (ok)
      LUA_INCDIR : C:/home/scoop/apps/lua/current/include (ok)
      LUA_LIBDIR : C:/home/scoop/apps/lua/current (not found)
                   ****************************************
                   Use the command

                      luarocks config variables.LUA_LIBDIR <dir>

                   to fix the location
                   ****************************************

   Configuration files:
      System  : C:/Program Files/luarocks/config-5.4.lua (not found)
      User    : C:\home\scoop\apps\luarocks\current\config.lua (ok)

   Rocks trees in use:
      C:/home/scoop/apps/luarocks/current/rocks
```

When ran with `--verbose` option, I see these lines which tell me Luarocks is searching for .lib files only, not .dll
```
fs.change_dir("lua-requests")
fs.exists("C:/home/scoop/apps/lua/current/lua5.4.lib")
fs.is_file("C:/home/scoop/apps/lua/current/lua5.4.lib")
fs.absolute_name("C:/home/scoop/apps/lua/current/lua5.4.lib")
fs.current_dir()
fs.is_file("C:/home/scoop/apps/lua/current/lua54.lib")
fs.absolute_name("C:/home/scoop/apps/lua/current/lua54.lib")
fs.current_dir()
fs.is_file("C:/home/scoop/apps/lua/current/lua-5.4.lib")
fs.absolute_name("C:/home/scoop/apps/lua/current/lua-5.4.lib")
fs.current_dir()
fs.is_file("C:/home/scoop/apps/lua/current/lua-54.lib")
fs.absolute_name("C:/home/scoop/apps/lua/current/lua-54.lib")
fs.current_dir()
fs.is_file("C:/home/scoop/apps/lua/current/lua.lib")
fs.absolute_name("C:/home/scoop/apps/lua/current/lua.lib")
fs.current_dir()
fs.pop_dir()
```
Even though `luarocks config` tells me that
`LIB_EXTENSION = "dll",`

**Comment by lost22git** [comment] 2022-10-09 22:58
Same problem and how to resolve it ?

**Comment by lost22git** [comment] 2022-10-09 23:14
`luarocks config variables.LUALIB "lua54.dll"` to solve it.

**Comment by yhslai** [comment] 2023-07-11 16:30
I mean, it has been 3 years...

**Comment by happanda** [comment] 2024-01-02 10:00
> `luarocks config variables.LUALIB "liblua54.a"` to solve it.

Looks like this solved the issue for me. At least, luarocks command shows LUA_LIBDIR as (ok). And trying to install some rocks tries to link the library to compiled C++ code.

**Comment by drunkenQCat** [comment] 2024-01-21 05:20
> > `luarocks config variables.LUALIB "liblua54.a"` to solve it.
> 
> Looks like this solved the issue for me. At least, luarocks command shows LUA_LIBDIR as (ok). And trying to install some rocks tries to link the library to compiled C++ code.

hey bro, your solution did works, thx a lot!

**Closed** 2024-02-20 06:51 UTC
Labels: windows
